# Generated by Django 5.0.3 on 2024-03-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectlist',
            name='project_code',
        ),
        migrations.AddField(
            model_name='projectlist',
            name='css_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='html_code',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='projectlist',
            name='js_code',
            field=models.TextField(null=True),
        ),
    ]
