# Generated by Django 5.0.3 on 2024-03-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_projectlist_project_code_projectlist_css_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='project_code',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
