# Generated by Django 5.0.3 on 2024-04-02 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_projectlist_project_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectlist',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='projects_contributed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectlist',
            name='fkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
